### PR TITLE
New boards are copies of default board

### LINKED ISSUE #77: Create copy of default board and vocabulary for new users
We currently allow anyone on the website to use the "guest" board, with board id 1. we want users to also "own" a default board when they first create an account so they aren't starting from scratch. however, we don't want users to edit this default board and affect others' default boards. 

as such, when a user account is created, we need to create a copy of the default board (board id 1) and all the words on it that they own and are allowed to modify.

this can probably happen in the [CreateAccountController](https://github.com/peeley/lucy/blob/master/app/Http/Controllers/CreateAccountController.php). I haven't tried it, but I believe models can be replicated like it says in the docs [here](https://laravel.com/docs/8.x/eloquent#replicating-models).

### PR DESCRIPTION
**Pull request by peeley**
Closes #77 

changes to the DB seed script were made, so the DB needs to be dropped and re-seeded w/ `docker-compose execute app php artisan migrate:fresh --seed`.

this can be tested on the home screen after logging in. when you make a new board, it should show up as `Default board`, and have all the same contents as the default board. however, in the URL the board id should be something other than `1`. also, if you make any changes to the board like editing or deleting a tile, if you go to another board (or the default board) you shouldn't see those changes since the contents of new boards are copies of the default board contents.

### CODE REVIEW

**Comment by eloisab17** [comment]
The create board functionality makes a copy of the default board, as expected.

I did notice some bugs at the board level. When editing a folder, submit returns the following error as a response:
   "message": "SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"text\" of relation \"folders\" does not exist\nLINE 1: update \"folders\" set \"color\" = $1, \"text\" = $2, \"updated_at\"...\n                                           ^ (SQL: update \"folders\" set \"color\" = #ffffff, \"text\" = food, \"updated_at\" = 2022-03-07 21:56:18 where \"id\" = 67)"

**Comment by eloisab17** [comment]
Also, sometimes when deleting a tile from the board the change needs to be refreshed. this error isnt always reproduced so Im not sure what could be going on there.

**Comment by peeley** [comment]
Fixed a data race w/ requests, so a page refresh is no longer needed after editing or deleting a tile. Also fixed a change in `BoardController`, folder names can be edited without errors.

**Comment by eloisab17** [comment]
looks good!

**Pull request merged**
