### PR TITLE
Implement dark theme

### PR DESCRIPTION
**Pull request by Mr78nine**
First stab at dark theme. Known bug: sun/moon icnons not showing  under /create-account

### CODE REVIEW

**Comment by peeley** [comment]
Looks like the theme and toggles aren't present on `/about-us` or the board screens `/board/{board_id}` :(

**Comment by eloisab17** [comment]
On my end, the sun/moon icons do show up under /create-account, but not on the guest page with the default board.

I dont know if this is intended, but when I logged out it switched from dark mode to light mode. It doesnt switch if you log out with light mode selected.

Also, for the dark mode on the /home page, the text should probably also be white.

**Comment by peeley** [comment]
> I dont know if this is intended, but when I logged out it switched from dark mode to light mode. It doesnt switch if you log out with light mode selected.

I think this might be caused by the light/dark mode toggle being stored in the session, and the session gets cleared out when the user logs out. `LoginController` is where the call to `$request->session()->invalidate()` happens - can't remember exactly why I added that, but maybe we could just remove the session invalidation so the dark/light preference persists.

**Comment by Mr78nine** [comment]
Working on resolving conflicts locally, not ready for merge....

**Comment by Mr78nine** [comment]
I think it's ok to invalidate the session when the user logs out, from what I can find online it seems to be good  practice. In the future we can store light/dark theme as a settings option as well a session variable so that the theme persists through login/logout and page refreshes.

**Comment by Mr78nine** [comment]
Ahh wait not ready, some text is still dark-on-dark

**Comment by eloisab17** [comment]
So this is what the guest board looks like on darkmode:
image
This is what it looks like on light mode:
image

**Comment by eloisab17** [comment]
It looks like the styling of the toggle is getting lost in light mode. also the placement of the toggle in light mode is different for every screen. for example:
image
image
image
image

**Comment by Mr78nine** [comment]
Fixed the styling issues with the toggle. I think @lvs-vong might have some input on some light theme styles looking kinda wack.

image
image

**Comment by eloisab17** [comment]
Found some dark-on-dark text on the home screen.
image

Also, the font on the about us page on dark mode isnt the same as light mode (serif vs san serif)
image
image

**Comment by lvs-vong** [comment]
Looks like the create-account.blade.php is an outdated version. The main thing causing that verify password field to be glitchy is because the css class is supposed to be "create-account create-account-input" instead of "create-account-input-button".

Also the Back button is supposed to be above the "Create Your Account" title

**Comment by Mr78nine** [comment]
Fixed style changes. Looks good on my end.

**Comment by lvs-vong** [comment]
image
Looks like the the board screen is still bugged for the light mode on my end. 
I think it is because of the missing link to the board.css on the board.blade.php
Everything else looks great.

**Comment by Mr78nine** [comment]
@lvs-vong I can't see the board stylings since I'm having trouble viewing the board but I applied your suggested change. Hopefully looks good?

**Comment by lvs-vong** [comment]
All good now

**Pull request merged**
