### PR TITLE
Pres words

### PR DESCRIPTION
**Pull request by RenSchuon**
Inside the talker folder we should now have a folder named "presentation" and inside that folder will be words on three lines containing all the words needed for demo phrases, aside from the "new" word that will be added in demo

### CODE REVIEW

**Comment by RenSchuon** [comment]
Dislexia errors fixed

**Comment by eloisab17** [comment]
Hey sorry for not getting around to this earlier. Did we still want to merge since the presentation is done? We could also use this for longer video.

**Comment by eloisab17** [comment]
Also looks good on my end, so feel free to merge whenever

**Comment by eloisab17** [comment]
Where is "I want" on the board? I wanted to make sure the changes were reflected after I reseeded the board but I couldn't find it.

**Comment by eloisab17** [comment]
looks good

**Pull request merged**
