### PR TITLE
Allow users to export boards as `.obf` files

### PR DESCRIPTION
**Pull request by peeley**
Ran into a pretty big snag on this - there's no way to test that this works. I followed the [spec](https://www.openboardformat.org/docs#) to a T, and tried to use OpenAAC's `.obf` [validator](https://www.openboardformat.org/tools), but it looks like it's broken :/

I'm getting a vague `Cannot parse as JSON` error when I upload the file. I've triple checked, and the file that is downloaded is 100% a valid JSON blob. I can also see other users ([1](https://github.com/open-aac/openboardformat/issues/2), [2](https://github.com/open-aac/openboardformat/issues/1)) are having trouble with this.

Regardless, you can see the export link on the home screen right under the edit/delete links. Once you click that, you can inspect the downloaded file and see all the info.

### CODE REVIEW

**Comment by peeley** [comment]
just tried out the only other free AAC supporting `.obf` imports (https://app.cboard.io/), and even the example `.obf` from the spec document results in this blank board titled `SYNTAXERROR`.

Screen Shot 2022-04-20 at 1 42 30 AM
 
the good news - this feature works just as well in our app as it does in everyone else's!

**Comment by peeley** [comment]
okay nvm, turns out the example in the board spec was improperly formatted (extra comma somewhere), and there was a bug in my code. here's CBoard, another AAC, using the default board:

Screen Shot 2022-04-20 at 1 56 45 AM

**Comment by eloisab17** [comment]
functionality works great on my end. One small thing though, the export board button looks a little weird, like theres two buttons stacked on top of each other.
image

**Comment by peeley** [comment]
> functionality works great on my end. One small thing though, the export board button looks a little weird, like theres two buttons stacked on top of each other. image

Updated styling, should look better now. There's still a weird orange hover effect over the link text, but it's not noticable (I'm not sure if you can even remove hover colors for links anyway)

**Comment by eloisab17** [comment]
looks good!

**Pull request merged**
