### PR TITLE
Update voice volume

### PR DESCRIPTION
**Pull request by eloisab17**
When users adjust the audio level settings, it adjusts the volume of the voice. 

The default volume is set to 100, (full volume) which is the case for the guest board as well.

You'll need to rerun the migrations since I made a change to the default audio level in the user settings table.

### CODE REVIEW

**Comment by lvs-vong** [comment]
The volume doesn't seem to change on my end.
I can see the audio level change in the dev tools though

**Comment by lvs-vong** [comment]
Although I think the default audio level should be 50 rather than 100.

**Comment by eloisab17** [comment]
> Although I think the default audio level should be 50 rather than 100.

I set it to 100 in case the audio on the users device isn't turned up all the way, but I can change still if you'd like

**Comment by lvs-vong** [comment]
> d

Then it's fine to just leave it as it is

**Pull request merged**
