### PR TITLE
Add tiles

### PR DESCRIPTION
**Pull request by eloisab17**
Adds icons to the default board.

Steps:

Run the following:
composer install

Set up docker, npm run dev and run watch like normal.

rerun migrations and seed database:
docker compose exec app php artisan migrate:fresh --seed

create a symbolic link between storage and public:
docker-compose exec app php artisan storage:link

After that, you should see the icons added to the default board.

### CODE REVIEW

**Comment by peeley** [comment]
Can you add `composer.json` after requiring `doctrine/dbal`? That way you can just run `composer install` to get the package, instead of explicitly running `composer require`.

**Comment by eloisab17** [comment]
I went ahead and added doctrine/dbal to the require section in composer.json.

That will include the package when running composer install, correct?

**Comment by peeley** [comment]
> I went ahead and added doctrine/dbal to the require section in composer.json.
> 
> That will include the package when running composer install, correct?

Yep, it'll just get installed automatically on the next `composer install`.

**Comment by eloisab17** [comment]
Had to add a couple things back in after merging main into the branch. Ready for review

**Comment by peeley** [comment]
Pushed a commit to update the icon URLs after moving them from `Icons` to `images` in another branch.

I noticed that some of the icons are present, like the neutral pronouns, but others are missing and blank. Do we have those yet, or are those filepaths just placeholders?

**Comment by eloisab17** [comment]
Oh, those are blank because the filepaths got messed up it looks like. I'll fix that.

**Comment by eloisab17** [comment]
All fixed. Reseeding the board should show the icons now.

**Comment by peeley** [comment]
> Oh, those are blank because the filepaths got messed up it looks like. I'll fix that.

Oh yeah, I moved all the images in `storage/app/public/Icons` into `storage/app/public/images` in the last PR that got merged. What I meant was that the images themselves haven't been committed to the repo - you might have to run `git add -f` to force add them, since `storage/*` is in `.gitignore`.

**Comment by eloisab17** [comment]
Committed the images to the repo. Do they need to be moved into the images folder as well?

**Comment by peeley** [comment]
> Committed the images to the repo. Do they need to be moved into the images folder as well? Right now most of them are in the Icons folder.

Nope, I just thought it'd be handy to have them all in one place.

Looks great now! Feel free to merge whenever

**Pull request merged**
