### PR TITLE
guided-use (2)

### PR DESCRIPTION
**Pull request by lvs-vong**
Same thing as last PR #125:

You have to recompile the js and css:
docker-compose exec app run watch

You also have to rerun the migrations:
docker-compose exec app php artisan migrate:fresh --seed

The default setting for the guided is set to on and it will activate after 30 seconds of idle time while on the board screen.
Users can change this in the settings. (Guests cannot change it though)

### CODE REVIEW

**Comment by lvs-vong** [comment]
Should have everything discussed done/fixed . Let me know if I forgot something or there are more bugs.

**Comment by eloisab17** [comment]
I dont get the option to change the guided use threshold in settings.
image

**Comment by lvs-vong** [comment]
Try now it now

**Comment by eloisab17** [comment]
the idle threshold is there! although the text for the lower button is now larger 
image

**Comment by eloisab17** [comment]
its fine when hovering, though.

image

**Comment by eloisab17** [comment]
other than that, guided use is working as expected!

**Comment by lvs-vong** [comment]
Should the setting css be a separate PR or should I fix it in this one?

**Comment by eloisab17** [comment]
it can be a separate one if you want. feel free to merge

**Pull request merged**
